#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs/
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

# data_dir = "/var/lib/vector"

# Vector's API for introspection
# Try it out with the `vector top` command
[api]
enabled = true
address = "127.0.0.1:8686"

# Dummy Apache formatted logs
[sources.dummy_logs]
type = "generator"
format = "syslog"
interval = 1

# Parse Apache formatted logs
# See the Remap reference: https://vector.dev/docs/reference/remap/
[transforms.parse_logs]
type = "remap"
source = '''
<<<<<<< HEAD
. = parse_syslog(.message)
=======
. = parse_apache_log(.message)
>>>>>>> 917c20a56 (Use correct Remap function)
'''

# Host-level metrics (cpu, memory, disk, etc)
[sources.host_metrics]
type = "host_metrics"

# Vector's own internal metrics
[sources.internal_metrics]
type = "internal_metrics"

# Print it all out for inspection
[sinks.print]
type = "console"
inptus = ["parse_logs", "host_metrics", "internal_metrics"]
